lexik_jwt_authentication:
    #secret_key: '%env(JWT_SECRET_KEY)%'
    #pass_phrase: '%env(JWT_PASSPHRASE)%'
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' 
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  
    pass_phrase:      '%env(JWT_PASSPHRASE)%'
    #token_ttl:        3600
    user_identity_field: email
    # token encoding/decoding settings
    encoder:
        # token encoder/decoder service - default implementation based on the lcobucci/jwt library
        service:            lexik_jwt_authentication.encoder.lcobucci

        # encryption algorithm used by the encoder service
        signature_algorithm: HS512
